/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Arrow: typeof import('./../components/Arrow/index.vue')['default']
    HomeFooter: typeof import('./../components/HomeFooter/index.vue')['default']
    HomeTitle: typeof import('./../components/HomeTitle/index.vue')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconCustomMenu: typeof import('~icons/custom/menu')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    PolicyPage: typeof import('./../components/PolicyPage/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
